examples/simple/books/urls.py
from django.conf.urls import url

from .views import (
    AddAuthorsToBookView,
    AuthorListView,
    AuthorListJSONView,
    AuthorListValuesView,
    AuthorListValuesWithCountsView,
    AuthorListWithCountsView,
    CreateAuthorsView,
    BookListView,
    BookListValuesView,
    BookListWithCountsView,
    PublisherIDsView,
    PublisherListView,
    UpdateBooksView,
    IndexView,
)

__all__ = ('urlpatterns',)


urlpatterns = [
    # Authors list
    url(r'^authors/$', AuthorListView.as_view(), name='books.authors'),

    # Authors list (more efficient)
    url(r'^authors-values/$',
        AuthorListValuesView.as_view(),
        name='books.authors_values'),

    # Authors list (with counts)
    url(r'^authors-with-counts/$',
        AuthorListWithCountsView.as_view(),
        name='books.authors_with_counts'),

    # Authors list (values with counts)
    url(r'^authors-values-with-counts/$',
        AuthorListValuesWithCountsView.as_view(),
        name='books.authors_values_with_counts'),

    # Authors list in JSON format
    url(r'^authors-json/$',
        AuthorListJSONView.as_view(),
        name='books.authors_json'),

    # Books list
    url(r'^books/$', BookListView.as_view(), name='books.books'),

    # Books list (with counts)
    url(r'^books-with-counts/$',
        BookListWithCountsView.as_view(),
        name='books.books_with_counts'),

    # Books list (more efficient)
    url(r'^books-values/$',
        view=BookListValuesView.as_view(),
        name='books.books_values'),

    # Publishers list
    url(r'^publishers/$',
        PublisherListView.as_view(),
        name='books.publishers'),

    # Publisher IDs
    url(r'^publisher-ids/$',
        PublisherIDsView.as_view(),
        name='books.publisher_ids'),

    # Create authors view
    url(r'^create-authors/$',
        CreateAuthorsView.as_view(),
        name='books.create_authors'),

    # Add authors to a book view
    url(r'^add-authors-to-book/$',
        AddAuthorsToBookView.as_view(),
        name='books.add_authors_to_book'),

    # Update books view
    url(r'^update-books/$',
        UpdateBooksView.as_view(),
        name='books.update_books'),

    # Index view
    url(r'^$', IndexView.as_view(), name='books.index'),
]

examples/simple/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.views.generic import TemplateView

from nine import versions

from books import urls as books_urls
from search_indexes import urls as search_index_urls

__all__ = ('urlpatterns',)

admin.autodiscover()

urlpatterns = []
urlpatterns_args = []

if versions.DJANGO_GTE_2_0:
    urlpatterns_args += [
        url(r'^admin/', admin.site.urls),
    ]
else:
    urlpatterns_args += [
        url(r'^admin/', include(admin.site.urls)),
    ]

urlpatterns_args += [
    # Books URLs
    url(r'^books/', include(books_urls)),

    # Search URLs
    url(r'^search/', include(search_index_urls)),

    # Home page
    url(r'^$', TemplateView.as_view(template_name='home.html')),
]

urlpatterns += urlpatterns_args[:]

# Serving media and static in debug/developer mode.
if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

    if settings.DEBUG_TOOLBAR is True:
        import debug_toolbar

        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

examples/simple/books/models/address.py
from __future__ import unicode_literals

from django.db import models
from django_elasticsearch_dsl_drf.wrappers import dict_to_obj

__all__ = ('Address',)


class Address(models.Model):
    """Address."""

    street = models.CharField(max_length=255)
    house_number = models.CharField(max_length=60)
    appendix = models.CharField(max_length=30, null=True, blank=True)
    zip_code = models.CharField(max_length=60)
    city = models.ForeignKey('books.City', on_delete=models.CASCADE)
    latitude = models.DecimalField(
        null=True,
        blank=True,
        decimal_places=15,
        max_digits=19,
        default=0
    )
    longitude = models.DecimalField(
        null=True,
        blank=True,
        decimal_places=15,
        max_digits=19,
        default=0
    )
    planet = models.ForeignKey('books.Planet',
                               null=True,
                               blank=True,
                               on_delete=models.CASCADE)

    class Meta:
        """Meta options."""

        ordering = ["id"]

    def __str__(self):
        return "{} {} {} {}".format(
            self.street,
            self.house_number,
            self.appendix,
            self.zip_code
        )

    @property
    def location_field_indexing(self):
        """Location for indexing.

        Used in Elasticsearch indexing/tests of `geo_distance` native filter.
        """
        return {
            'lat': self.latitude,
            'lon': self.longitude,
        }

    @property
    def country_indexing(self):
        """Country data (nested) for indexing.

        Example:

        >>> mapping = {
        >>>     'country': {
        >>>         'name': 'Netherlands',
        >>>         'city': {
        >>>             'name': 'Amsterdam',
        >>>         }
        >>>     }
        >>> }

        :return:
        """
        wrapper = dict_to_obj({
            'name': self.city.country.name,
            'city': {
                'name': self.city.name
            }
        })

        return wrapper

    @property
    def continent_indexing(self):
        """Continent data (nested) for indexing.

        Example:

        >>> mapping = {
        >>>     'continent': {
        >>>         'id': 2,
        >>>         'name': 'Asia',
        >>>         'country': {
        >>>             'id': 3,
        >>>             'name': 'Netherlands',
        >>>             'city': {
        >>>                 'id': 5,
        >>>                 'name': 'Amsterdam',
        >>>             }
        >>>         }
        >>>     }
        >>> }

        :return:
        """
        wrapper = dict_to_obj({
            'id': self.city.country.continent.id,
            'name': self.city.country.continent.name,
            'country': {
                'id': self.city.country.id,
                'name': self.city.country.name,
                'city': {
                    'id': self.city.id,
                    'name': self.city.name,
                }
            }
        })

        return wrapper

    @property
    def galaxy_indexing(self):
        """Galaxy data (nested) for indexing.

        Example:

        >>> mapping = {
        >>>     'galaxy': {
        >>>         'id': 2,
        >>>         'name': 'Milky Way',
        >>>         'planet': {
        >>>             'id': 3,
        >>>             'name': 'Earth',
        >>>         }
        >>>     }
        >>> }

        :return:
        """
        wrapper = dict_to_obj({
            'id': self.planet.galaxy.id,
            'name': self.planet.galaxy.name,
            'planet': {
                'id': self.planet.id,
                'name': self.planet.name,
            }
        })

        return wrapper

examples/simple/books/models/book.py
from django.db import models
from django.conf import settings

from ..constants import (
    BOOK_PUBLISHING_STATUS_CHOICES,
    BOOK_PUBLISHING_STATUS_DEFAULT,
)

__all__ = ('Book',)


class Book(models.Model):
    """Book."""

    title = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    summary = models.TextField(null=True, blank=True)
    authors = models.ManyToManyField('books.Author', related_name='books')
    publisher = models.ForeignKey(
        'books.Publisher',
        related_name='books',
        on_delete=models.CASCADE
    )
    publication_date = models.DateField()
    state = models.CharField(
        max_length=100,
        choices=BOOK_PUBLISHING_STATUS_CHOICES,
        default=BOOK_PUBLISHING_STATUS_DEFAULT
    )
    isbn = models.CharField(max_length=100, unique=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    pages = models.PositiveIntegerField(default=200)
    stock_count = models.PositiveIntegerField(default=30)
    tags = models.ManyToManyField(
        'books.Tag',
        related_name='books',
        blank=True
    )
    created = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    class Meta:
        """Meta options."""

        ordering = ["isbn"]

    def __str__(self):
        return self.title

    @property
    def publisher_indexing(self):
        """Publisher for indexing.

        Used in Elasticsearch indexing.
        """
        if self.publisher is not None:
            return self.publisher.name

    @property
    def tags_indexing(self):
        """Tags for indexing.

        Used in Elasticsearch indexing.
        """
        return [tag.title for tag in self.tags.all()]

    @property
    def null_field_indexing(self):
        """null_field for indexing.

        Used in Elasticsearch indexing/tests of `isnull` functional filter.
        """
        return None

    @property
    def created_indexing(self):
        return self.created.strftime(settings.ELASTICSEARCH_DATETIME_FORMAT)

examples/simple/books/models/galaxy.py
from __future__ import unicode_literals

from django.db import models

__all__ = ('Galaxy',)


class Galaxy(models.Model):
    """Galaxy."""

    name = models.CharField(max_length=255)

    class Meta:
        """Meta options."""

        ordering = ["id"]

    def __str__(self):
        return self.name

examples/simple/books/views.py
from django.db.models import Avg, Count, DecimalField, F, Max, Min, Sum
from django.views.generic import ListView, TemplateView

from ormex.aggregations import GroupConcat

import factories

from .mixins import JSONResponseMixin
from .models import Author, Book, Publisher


__all__ = (
    'AddAuthorsToBookView',
    'AuthorListView',
    'AuthorListJSONView',
    'AuthorListValuesView',
    'AuthorListValuesWithCountsView',
    'AuthorListWithCountsView',
    'CreateAuthorsView',
    'BookListView',
    'BookListValuesView',
    # 'OrderLineListView',
    # 'OrderListView',
    'PublisherIDsView',
    'PublisherListView',
    'UpdateBooksView',
    'IndexView',
)


class IndexView(TemplateView):
    """Index."""

    template_name = 'books/index.html'


class PublisherListView(ListView):
    """Publishers."""

    model = Publisher


class BookListView(ListView):
    """Books."""

    model = Book

    def get_queryset(self):
        """Get queryset."""
        return self.model.objects.all() \
            .select_related('publisher') \
            .prefetch_related('authors') \
            .only('id',
                  'title',
                  'pages',
                  'price',
                  'publisher__id',
                  'publisher__name',
                  'authors__id',
                  'authors__name')


class BookListWithCountsView(ListView):
    """Books list with counts."""

    model = Book
    template_name = 'books/book_list_with_counts.html'

    def get_queryset(self):
        """Get queryset."""
        return self.model.objects.all() \
            .select_related('publisher') \
            .prefetch_related('authors') \
            .only('id',
                  'title',
                  'pages',
                  'price',
                  'publisher__id',
                  'publisher__name',
                  'authors__id',
                  'authors__name') \
            .annotate(
                price_per_page=Sum(
                    F('price') / F('pages'),
                    output_field=DecimalField(decimal_places=2)
                )
            )


class BookListValuesView(ListView):
    """Books."""

    model = Book
    template_name = 'books/book_list_values.html'

    def get_queryset(self):
        """Get queryset."""
        return self.model.objects.all() \
            .values('id',
                    'title',
                    'pages',
                    'price',
                    'publisher__id',
                    'publisher__name') \
            .annotate(
                authors__name=GroupConcat('authors__name', separator=', ')
            ) \
            .distinct()


class AuthorListView(ListView):
    """Authors."""

    model = Author


class AuthorListWithCountsView(ListView):
    """Authors list with counts."""

    model = Author
    template_name = 'books/author_list_with_counts.html'

    def get_queryset(self):
        """Get queryset."""
        return self.model.objects.all() \
            .only('id',
                  'salutation',
                  'name',
                  'email') \
            .annotate(
                number_of_books=Count('books'),
                first_book_published_on=Min('books__publication_date'),
                last_book_published_on=Max('books__publication_date'),
                lowest_book_price=Min('books__price'),
                highest_book_price=Max('books__price'),
                average_book_price=Avg('books__price'),
                average_number_of_pages_per_book=Avg('books__pages'),
                number_of_books_sold=Count('books__order_lines'),
                total_amount_earned=Sum(
                    'books__order_lines__book__price'
                )
            )


class AuthorListValuesView(ListView):
    """Authors list (using ``values``)."""

    model = Author
    template_name = 'books/author_list_values.html'

    def get_queryset(self):
        """Get queryset."""
        return self.model.objects.all() \
            .values('id',
                    'salutation',
                    'name',
                    'email')


class AuthorListValuesWithCountsView(ListView):
    """Authors list (using ``values``) with counts."""

    model = Author
    template_name = 'books/author_list_values_with_counts.html'

    def get_queryset(self):
        """Get queryset."""
        return self.model.objects.all() \
            .annotate(
                number_of_books=Count('books'),
                first_book_published_on=Min('books__publication_date'),
                last_book_published_on=Max('books__publication_date'),
                lowest_book_price=Min('books__price'),
                highest_book_price=Max('books__price'),
                average_book_price=Avg('books__price'),
                average_number_of_pages_per_book=Avg('books__pages'),
                number_of_books_sold=Count('books__order_lines'),
                total_amount_earned=Sum('books__order_lines__book__price')
            ) \
            .values('id',
                    'salutation',
                    'name',
                    'email',
                    'number_of_books',
                    'first_book_published_on',
                    'last_book_published_on',
                    'lowest_book_price',
                    'highest_book_price',
                    'average_book_price',
                    'average_number_of_pages_per_book',
                    'number_of_books_sold',
                    'total_amount_earned')


class AuthorListJSONView(JSONResponseMixin, TemplateView):
    """Authors list JSON response."""

    model = Author

    def get_data(self, context):
        """Get queryset."""
        return list(
            self.model.objects.all()
                .values('id',
                        'salutation',
                        'name',
                        'email')
        )

    def render_to_response(self, context, **response_kwargs):
        """Render."""
        response_kwargs.update({'safe': False})

        return self.render_to_json_response(context, **response_kwargs)


class CreateAuthorsView(TemplateView):
    """Create authors view."""

    template_name = 'books/create_authors.html'

    def get_context_data(self, **kwargs):
        """Get context data."""
        authors_list = []
        for __i in range(1, 50):
            author = factories.AuthorFactory.build()
            authors_list.append(author)

        Author.objects.bulk_create(authors_list)

        return {'object_list': authors_list}


class AddAuthorsToBookView(TemplateView):
    """Add authors to a book view."""

    template_name = 'books/add_authors_to_book.html'

    def get_context_data(self, **kwargs):
        """Get context data."""
        book = Book.objects.select_related('publisher').first()

        authors = Author.objects.filter()[:50]

        book.authors.add(*authors)

        return {'object_list': [book], 'book_authors': authors}


class PublisherIDsView(TemplateView):
    """List of Publisher IDs."""

    template_name = 'books/publisher_ids.html'

    def get_context_data(self, **kwargs):
        """Get context data."""
        books = Book.objects.filter()[:50]

        publisher_ids = [__b.publisher_id for __b in books]

        return {'object_list': publisher_ids}


class UpdateBooksView(TemplateView):
    """Update books view.."""

    template_name = 'books/update_books.html'

    def get_context_data(self, **kwargs):
        """Get context data."""
        # Just get some book IDs.
        book_ids = Book.objects.values_list('id', flat=True)[:50]

        books = Book.objects \
            .filter(id__in=book_ids) \
            .update(stock_count=F('stock_count') - 1)

        return {'number_of_books_updated': books}

examples/simple/books/templates/books/add_authors_to_book.html
{% extends "books/book_list.html" %}
{% block meta-title %}Add authors to a book{% endblock %}

{% block nav-menu-items %}
    {% with True as books_add_authors_to_book_is_active %}
        {% include "snippets/menu_items.html" %}
    {% endwith %}
{% endblock nav-menu-items %}

{% block main-content %}
    <h2>Books</h2>
    <table>
        <thead>
        <tr>
            <th>Book</th>
            <th>Authors</th>
            <th>Publisher</th>
            <th>Number of pages</th>
            <th>Price</th>
        </tr>
        </thead>
        {% for book in object_list %}
            <tr>
                <td>{{ book.title }}</td>
                <td>{% for author in book_authors %}{{ author.name }},{% endfor %}</td>
                <td>{{ book.publisher.name }}</td>
                <td>{{ book.pages }}</td>
                <td>{{ book.price }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}
{% block sidebar-content %}{% endblock sidebar-content %}

examples/simple/books/templates/books/author_list.html
{% extends "base.html" %}
{% block meta-title %}Authors{% endblock %}

{% block nav-menu-items %}
    {% with True as books_authors_is_active %}
        {% include "snippets/menu_items.html" %}
    {% endwith %}
{% endblock nav-menu-items %}

{% block main-content %}
    <h2>Authors</h2>
    <table>
        <thead>
        <tr>
            <th>Salutation</th>
            <th>Name</th>
            <th>E-mail</th>
        </tr>
        </thead>
        {% for author in object_list %}
            <tr>
                <td>{{ author.salutation }}</td>
                <td>{{ author.name }}</td>
                <td>{{ author.email }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}
{% block sidebar-content %}{% endblock sidebar-content %}

examples/simple/books/templates/books/author_list_values.html
{% extends "books/author_list.html" %}
{% block meta-title %}Authors (values){% endblock %}

{% block nav-menu-items %}
    {% with True as books_authors_values_is_active %}
        {% include "snippets/menu_items.html" %}
    {% endwith %}
{% endblock nav-menu-items %}

examples/simple/books/templates/books/author_list_values_with_counts.html
{% extends "base.html" %}
{% load humanize %}
{% block meta-title %}Authors (values with counts){% endblock %}

{% block nav-menu-items %}
    {% with True as books_authors_values_with_counts_is_active %}
        {% include "snippets/menu_items.html" %}
    {% endwith %}
{% endblock nav-menu-items %}

{% block main-content %}
    <h2>Authors</h2>
    <table>
        <thead>
        <tr>
            <th>Salutation</th>
            <th>Name</th>
            <th>E-mail</th>
            <th>Number of books</th>
            <th>First book published on</th>
            <th>Last book published on</th>
            <th>Lowest book price</th>
            <th>Highest book price</th>
            <th>Average book price</th>
            <th>Average number of pages per book</th>
            <th>Number of books sold</th>
            <th>Total amount earned</th>
        </tr>
        </thead>
        {% for author in object_list %}
            <tr>
                <td>{{ author.salutation }}</td>
                <td>{{ author.name }}</td>
                <td>{{ author.email }}</td>
                <td>{{ author.number_of_books }}</td>
                <td>{{ author.first_book_published_on|date }}</td>
                <td>{{ author.last_book_published_on|date }}</td>
                <td>{{ author.lowest_book_price|floatformat:2 }}</td>
                <td>{{ author.highest_book_price|floatformat:2 }}</td>
                <td>{{ author.average_book_price|floatformat:2 }}</td>
                <td>{{ author.average_number_of_pages_per_book|floatformat:0 }}</td>
                <td>{{ author.number_of_books_sold }}</td>
                <td>{{ author.total_amount_earned|intcomma }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}
{% block sidebar-content %}{% endblock sidebar-content %}

examples/simple/books/templates/books/author_list_with_counts.html
{% extends "base.html" %}
{% load humanize %}
{% block meta-title %}Authors (with counts){% endblock %}

{% block nav-menu-items %}
    {% with True as books_authors_with_counts_is_active %}
        {% include "snippets/menu_items.html" %}
    {% endwith %}
{% endblock nav-menu-items %}

{% block main-content %}
    <h2>Authors</h2>
    <table>
        <thead>
        <tr>
            <th>Salutation</th>
            <th>Name</th>
            <th>E-mail</th>
            <th>Number of books</th>
            <th>First book published on</th>
            <th>Last book published on</th>
            <th>Lowest book price</th>
            <th>Highest book price</th>
            <th>Average book price</th>
            <th>Average number of pages per book</th>
            <th>Number of books sold</th>
            <th>Total amount earned</th>
        </tr>
        </thead>
        {% for author in object_list %}
            <tr>
                <td>{{ author.salutation }}</td>
                <td>{{ author.name }}</td>
                <td>{{ author.email }}</td>
                <td>{{ author.number_of_books }}</td>
                <td>{{ author.first_book_published_on|date }}</td>
                <td>{{ author.last_book_published_on|date }}</td>
                <td>{{ author.lowest_book_price|floatformat:2 }}</td>
                <td>{{ author.highest_book_price|floatformat:2 }}</td>
                <td>{{ author.average_book_price|floatformat:2 }}</td>
                <td>{{ author.average_number_of_pages_per_book|floatformat:0 }}</td>
                <td>{{ author.number_of_books_sold }}</td>
                <td>{{ author.total_amount_earned|intcomma }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}
{% block sidebar-content %}{% endblock sidebar-content %}

examples/simple/books/templates/books/book_list.html
{% extends "base.html" %}
{% block meta-title %}Books{% endblock %}

{% block nav-menu-items %}
    {% with True as books_books_is_active %}
        {% include "snippets/menu_items.html" %}
    {% endwith %}
{% endblock nav-menu-items %}

{% block main-content %}
    <h2>Books</h2>
    <table>
        <thead>
        <tr>
            <th>Book</th>
            <th>Authors</th>
            <th>Publisher</th>
            <th>Number of pages</th>
            <th>Price</th>
        </tr>
        </thead>
        {% for book in object_list %}
            <tr>
                <td>{{ book.title }}</td>
                <td>{% for author in book.authors.all %}{{ author.name }}{% if not forloop.last %}, {% endif %}{% endfor %}</td>
                <td>{{ book.publisher.name }}</td>
                <td>{{ book.pages }}</td>
                <td>{{ book.price }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}
{% block sidebar-content %}{% endblock sidebar-content %}

examples/simple/books/templates/books/book_list_values.html
{% extends "base.html" %}
{% block meta-title %}Books (values){% endblock %}

{% block nav-menu-items %}
    {% with True as books_books_values_is_active %}
        {% include "snippets/menu_items.html" %}
    {% endwith %}
{% endblock nav-menu-items %}

{% block main-content %}
    <h2>Books</h2>
    <table>
        <thead>
        <tr>
            <th>Book</th>
            <th>Authors</th>
            <th>Publisher</th>
            <th>Number of pages</th>
            <th>Price</th>
        </tr>
        </thead>
        {% for book in object_list %}
            <tr>
                <td>{{ book.title }}</td>
                <td>{{ book.authors__name}}</td>
                <td>{{ book.publisher__name }}</td>
                <td>{{ book.pages }}</td>
                <td>{{ book.price }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}
{% block sidebar-content %}{% endblock sidebar-content %}

examples/simple/books/templates/books/book_list_with_counts.html
{% extends "base.html" %}
{% block meta-title %}Books (with counts){% endblock %}

{% block nav-menu-items %}
    {% with True as books_books_with_counts_is_active %}
        {% include "snippets/menu_items.html" %}
    {% endwith %}
{% endblock nav-menu-items %}

{% block main-content %}
    <h2>Books</h2>
    <table>
        <thead>
        <tr>
            <th>Book</th>
            <th>Authors</th>
            <th>Publisher</th>
            <th>Number of pages</th>
            <th>Price</th>
            <th>Price per page</th>
        </tr>
        </thead>
        {% for book in object_list %}
            <tr>
                <td>{{ book.title }}</td>
                <td>{% for author in book.authors.all %}{{ author.name }},{% endfor %}</td>
                <td>{{ book.publisher.name }}</td>
                <td>{{ book.pages }}</td>
                <td>{{ book.price }}</td>
                <td>{{ book.price_per_page }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}
{% block sidebar-content %}{% endblock sidebar-content %}

examples/simple/books/templates/books/create_authors.html
{% extends "books/author_list.html" %}
{% block meta-title %}Create authors{% endblock %}

{% block nav-menu-items %}
    {% with True as books_create_authors_is_active %}
        {% include "snippets/menu_items.html" %}
    {% endwith %}
{% endblock nav-menu-items %}

examples/simple/books/templates/books/index.html
{% extends "home.html" %}
{% block meta-title %}Index{% endblock %}

examples/simple/books/templates/books/publisher_ids.html
{% extends "base.html" %}
{% block meta-title %}Publisher IDs{% endblock %}

{% block nav-menu-items %}
    {% with True as books_publisher_ids_is_active %}
        {% include "snippets/menu_items.html" %}
    {% endwith %}
{% endblock nav-menu-items %}

{% block main-content %}
    <h2>Publisher IDs</h2>
    <table>
        <thead>
        <tr>
            <th>Publisher ID</th>
        </tr>
        </thead>
        {% for publisher_id in object_list %}
            <tr>
                <td>{{ publisher_id }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}
{% block sidebar-content %}{% endblock sidebar-content %}

examples/simple/books/templates/books/publisher_list.html
{% extends "base.html" %}
{% block meta-title %}Publishers{% endblock %}

{% block nav-menu-items %}
    {% with True as books_publishers_is_active %}
        {% include "snippets/menu_items.html" %}
    {% endwith %}
{% endblock nav-menu-items %}

{% block main-content %}
    <h2>Publishers</h2>
    <table>
        <thead>
        <tr>
            <th>Name</th>
        </tr>
        </thead>
        {% for publisher in object_list %}
            <tr>
                <td>{{ publisher }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}
{% block sidebar-content %}{% endblock sidebar-content %}

examples/simple/books/templates/books/update_books.html
{% extends "base.html" %}
{% block meta-title %}Update books{% endblock %}

{% block nav-menu-items %}
    {% with True as books_update_books_is_active %}
        {% include "snippets/menu_items.html" %}
    {% endwith %}
{% endblock nav-menu-items %}

{% block main-content %}
    <h2>Update books</h2>
    <p>Number of books updated: {{ number_of_books_updated }}</p>
{% endblock %}
{% block sidebar-content %}{% endblock sidebar-content %}